import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from "@/context/AuthContext";
import DashboardLayout from "@/components/layouts/DashboardLayout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { User } from "lucide-react";
const AdminProfile = () => {
    const { user } = useAuth();
    return (_jsx(DashboardLayout, { children: _jsxs("div", { className: "space-y-6", children: [_jsx("h1", { className: "text-3xl font-bold text-foreground", children: "Admin Profile" }), _jsx(Card, { className: "p-8", children: _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-6", children: [_jsx("div", { className: "flex h-16 w-16 items-center justify-center rounded-lg bg-primary text-primary-foreground", children: _jsx(User, { className: "h-8 w-8" }) }), _jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-foreground", children: user?.displayName || "Admin User" }), _jsx("p", { className: "text-sm text-muted-foreground mt-1", children: user?.email || "admin@example.com" })] })] }), _jsxs("div", { className: "space-y-4 border-t pt-6", children: [_jsxs("div", { className: "grid grid-cols-1 gap-6 sm:grid-cols-2", children: [_jsxs("div", { className: "space-y-2", children: [_jsx(Label, { children: "Full Name" }), _jsx(Input, { defaultValue: user?.displayName || "" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { children: "Email" }), _jsx(Input, { type: "email", defaultValue: user?.email || "", disabled: true })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { children: "Department / Subject" }), _jsx(Input, { placeholder: "e.g., Computer Science" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { children: "Bio" }), _jsx("textarea", { className: "w-full rounded-md border border-border bg-background px-3 py-2 text-sm resize-none", rows: 4, placeholder: "Add your bio here..." })] }), _jsxs("div", { className: "flex gap-3 pt-4", children: [_jsx(Button, { children: "Save Changes" }), _jsx(Button, { variant: "outline", children: "Cancel" })] })] })] }) }), _jsxs(Card, { className: "p-8", children: [_jsx("h3", { className: "text-lg font-semibold text-foreground mb-4", children: "Account Settings" }), _jsxs("div", { className: "space-y-4", children: [_jsx(Button, { variant: "outline", className: "w-full justify-start", children: "Change Password" }), _jsx(Button, { variant: "outline", className: "w-full justify-start", children: "Two-Factor Authentication" }), _jsx(Button, { variant: "destructive", className: "w-full justify-start", children: "Delete Account" })] })] })] }) }));
};
export default AdminProfile;
